AWSTemplateFormatVersion: "2010-09-09"
Transform: AWS::Serverless-2016-10-31
Description: EKSphemeral is a simple EKS cluster manager

Globals:
  Function:
    Timeout: 30
  Api:
    Cors:
      AllowMethods: "'*'"
      AllowHeaders: "'*'"
      AllowOrigin: "'*'"

Resources:
  StatusFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: status
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /status
            Method: GET
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - s3:ListBucket
              - s3:GetBucket
              - s3:GetObject
              - s3:ListObjects
              Resource:
              - 'arn:aws:s3:::eks-cluster-meta/*'
              - 'arn:aws:s3:::eks-cluster-meta'
  CreateClusterFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: createcluster
      Runtime: go1.x
      Tracing: Active
      Events:
        CatchAll:
          Type: Api
          Properties:
            Path: /create
            Method: POST
      Policies:
        - AWSLambdaExecute
        - Version: '2012-10-17'
          Statement:
            - Effect: Allow
              Action:
              - eks:*
              Resource: '*'
            - Effect: Allow
              Action:
              - s3:PutObject
              Resource: 'arn:aws:s3:::eks-cluster-meta/*'
  DestroyClusterFunc:
    Type: AWS::Serverless::Function
    Properties:
      CodeUri: bin/
      Handler: destroycluster
      Runtime: go1.x
      Tracing: Active
      Events:
        Timer:
          Type: Schedule
          Properties:
            Schedule: rate(1 minute)

Outputs:
  EKSphemeralAPIEndpoint:
    Description: "The EKSphemeral HTTP API Gateway endpoint URL for Prod env"
    Value: !Sub "https://${ServerlessRestApi}.execute-api.${AWS::Region}.amazonaws.com/Prod"

