site_name: EKSphemeral
nav:
    - Home: index.md
    - CLI: cli.md
    - Web UI: ui.md
    - Architecture: arch.md
    - Develop: dev.md

theme:
    name: material

markdown_extensions:
    - toc:
        permalink: ' #'
    - admonition
    - def_list