site_name: EKSphemeral
nav:
    - Home: index.md
    - CLI: cli.md
    - Web UI: ui.md
    - Architecture: arch.md
    - Develop: dev.md

theme:
    name: 'material'
    custom_dir: 'theme'
    # favicon: 'assets/images/favicon.png'
    logo: 'assets/images/logo.png'
    #   icon: 'timelapse'
    palette:
      primary: 'orange'
      accent: 'orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash

markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true
