site_name: EKSphemeral
site_description: 'The EKS Ephemeral Cluster Manager'
site_author: 'Michael Hausenblas'
repo_name: 'mhausenblas/eksphemeral'
repo_url: 'https://github.com/mhausenblas/eksphemeral'
copyright: 'Copyright &copy; 2019 Amazon'
nav:
    - Home: index.md
    - CLI: cli.md
    - Web UI: ui.md
    - Architecture: arch.md
    - Develop: dev.md
    - FAQ: faq.md
theme:
    name: 'material'
    custom_dir: 'theme'
    # favicon: 'assets/images/favicon.png'
    logo: 'assets/images/logo.png'
    #   icon: 'timelapse'
    palette:
      primary: 'orange'
      accent: 'orange'
    highlightjs: true
    hljs_languages:
        - yaml
        - json
        - bash
markdown_extensions:
    - toc:
        permalink: true
    - admonition
    - codehilite:
        linenums: true
